"""add agent status columns and reprint

Revision ID: e22bade1285f
Revises: 9f0810e93958
Create Date: 2026-04-11 13:57:21.997151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22bade1285f'
down_revision: Union[str, None] = '9f0810e93958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('last_job_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('last_print_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('last_print_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('last_error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('reprint_from_job_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'reprint_from_job_id')
    op.drop_column('agents', 'last_error_message')
    op.drop_column('agents', 'last_error_at')
    op.drop_column('agents', 'last_print_completed_at')
    op.drop_column('agents', 'last_print_started_at')
    op.drop_column('agents', 'last_job_received_at')
    op.drop_column('agents', 'is_active')
    # ### end Alembic commands ###
